---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: iperf3-server-c
spec:
  replicas: 1
  selector:
    matchLabels:
      application: iperf3-server-c
  template:
    metadata:
      labels:
        application: iperf3-server-c
    spec:
      containers: 
        - image: quay.io/skupper/simple-iperf
          name: iperf3-server
          command:
            - iperf3
            - "-s"
          imagePullPolicy: IfNotPresent
